import type { InventoryItem, Recipe } from "./types";

const now = "2026-01-01T00:00:00.000Z";

function item(
  type: InventoryItem["type"],
  category: string,
  name: string,
  unit: string,
  par: number
): InventoryItem {
  const slug = `${type}-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;
  return { id: slug, type, name, category, unit, par, createdAt: now };
}

export function seedItems(): InventoryItem[] {
  const prep: Array<[string, string, string, number]> = [
    ["Soups & Sauces", "Shrimp, Crab & Crawfish Gumbo", "gal", 4],
    ["Soups & Sauces", "Soup of the Day", "gal", 3],
    ["Soups & Sauces", "Crawfish Joule Sauce", "qt", 4],
    ["Soups & Sauces", "Hollandaise", "qt", 3],
    ["Soups & Sauces", "Sriracha Hollandaise", "qt", 1],
    ["Soups & Sauces", "Buffalo Hollandaise", "qt", 1],
    ["Soups & Sauces", "Meuniere Sauce", "qt", 3],
    ["Soups & Sauces", "Bacon Meuniere", "qt", 2],
    ["Soups & Sauces", "House Remoulade", "qt", 2],
    ["Soups & Sauces", "Bearnaise", "qt", 2],
    ["Soups & Sauces", "Bacon Bearnaise", "qt", 2],
    ["Soups & Sauces", "Tasso Cream Sauce", "qt", 2],
    ["Soups & Sauces", "Crab Mornay", "qt", 2],
    ["Soups & Sauces", "Garlic Parmesan Sauce", "qt", 3],
    ["Soups & Sauces", "Sundried Tomato Pesto", "qt", 2],
    ["Soups & Sauces", "Alfredo", "qt", 3],
    ["Soups & Sauces", "Garlic Cream Sauce", "qt", 2],
    ["Soups & Sauces", "White Wine Demi Glaze", "qt", 2],
    ["Soups & Sauces", "Prime Rib Au Jus", "qt", 2],
    ["Soups & Sauces", "BBQ Shrimp Broth", "qt", 2],
    ["Soups & Sauces", "Chipotle Ranch", "qt", 2],
    ["Soups & Sauces", "Caper Dill Aioli", "qt", 1],
    ["Soups & Sauces", "Garlic Aioli", "qt", 1],
    ["Soups & Sauces", "Cucumber Wasabi", "pt", 2],
    ["Soups & Sauces", "Jezebel Sauce", "pt", 1],
    ["Soups & Sauces", "Mango Salsa", "qt", 2],
    ["Soups & Sauces", "Pear Chutney", "qt", 1],
    ["Soups & Sauces", "Bourbon Sauce", "qt", 1],
    ["Seafood Prep", "Lump Crab Cakes", "ea", 40],
    ["Seafood Prep", "Crab Meat Pie (assembled)", "ea", 12],
    ["Seafood Prep", "Fried Green Tomatoes (breaded)", "ea", 40],
    ["Seafood Prep", "Avocado Fries (breaded)", "portion", 12],
    ["Seafood Prep", "Panko Catfish Portions", "ea", 20],
    ["Seafood Prep", "Soft Shell Crabs (cleaned)", "ea", 12],
    ["Seafood Prep", "Peeled Gulf Shrimp", "lb", 15],
    ["Dips & Spreads", "Spinach & Artichoke Dip", "qt", 4],
    ["Dips & Spreads", "Smoked Tuna Dip", "qt", 3],
    ["Dips & Spreads", "Gouda Pimento Cheese", "qt", 3],
    ["Dips & Spreads", "Honey Pecan Brie (assembled)", "ea", 8],
    ["Dips & Spreads", "Guacamole", "qt", 2],
    ["Dressings", "Bleu Cheese Dressing", "qt", 2],
    ["Dressings", "Caesar Dressing", "qt", 3],
    ["Dressings", "Ranch", "qt", 2],
    ["Dressings", "Honey Mustard", "qt", 1],
    ["Dressings", "Raspberry Vinaigrette", "qt", 1],
    ["Dressings", "Strawberry Balsamic Reduction", "qt", 2],
    ["Dressings", "Poppyseed Dressing", "qt", 1],
    ["Dressings", "Red Wine Honey Vinaigrette", "qt", 1],
    ["Dressings", "Balsamic Vinaigrette", "qt", 1],
    ["Dressings", "Russian / Thousand Island", "qt", 1],
    ["Sides Prep", "Gouda Grits", "gal", 3],
    ["Sides Prep", "Cheesy White Grits", "gal", 3],
    ["Sides Prep", "Cream of Spinach", "gal", 2],
    ["Sides Prep", "Parmesan Risotto", "gal", 2],
    ["Sides Prep", "Yukon Mashed Potatoes", "gal", 2],
    ["Sides Prep", "House Garlic Croutons", "gal", 1],
    ["Breads & Batter", "Waffle Batter", "gal", 2],
    ["Breads & Batter", "Cheddar Chive Biscuits", "ea", 24],
    ["Breads & Batter", "Fresh Baked Sweet Bread", "ea", 18],
    ["Breads & Batter", "Hushpuppy Mix", "batch", 2],
    ["Desserts", "Chocolate Lava Cake", "ea", 16],
    ["Desserts", "Cheesecake Slices", "ea", 16],
    ["Desserts", "Tuxedo Bomb", "ea", 12],
    ["Desserts", "Pecan Pie Slices", "ea", 12],
    ["Desserts", "Key Lime Pie Slices", "ea", 12],
    ["Desserts", "Creme Brulee", "ea", 16],
    ["Desserts", "Homemade Bread Pudding", "pan", 2],
    ["Desserts", "Hot Chocolate Cheesecake", "ea", 10],
    ["Desserts", "Bananas Foster Bread Pudding", "pan", 1],
    ["Brunch", "Bloody Mary Mix", "gal", 3],
  ];

  const ordering: Array<[string, string, string, number]> = [
    ["Seafood", "Fresh Lump Crab Meat", "lb", 10],
    ["Seafood", "Gulf Shrimp 16/20", "lb", 20],
    ["Seafood", "Crawfish Tails", "lb", 8],
    ["Seafood", "Fresh Oysters", "dz", 15],
    ["Seafood", "Blue Crab Claws", "lb", 8],
    ["Seafood", "Wild Alaskan Salmon", "lb", 10],
    ["Seafood", "Sushi Grade Ahi Tuna", "lb", 6],
    ["Seafood", "Mississippi Catfish", "lb", 10],
    ["Seafood", "Grouper", "lb", 6],
    ["Seafood", "Mahi Mahi", "lb", 6],
    ["Seafood", "Snapper", "lb", 5],
    ["Seafood", "Seabass", "lb", 4],
    ["Seafood", "Sea Scallops", "lb", 5],
    ["Seafood", "Soft Shell Crabs", "ea", 18],
    ["Seafood", "Maine Lobster Meat", "lb", 3],
    ["Seafood", "Snow Crab Clusters", "ea", 10],
    ["Beef & Pork", "Filet Mignon", "lb", 12],
    ["Beef & Pork", "USDA Prime Ribeye 12 oz", "ea", 16],
    ["Beef & Pork", "Prime Rib Roast", "lb", 20],
    ["Beef & Pork", "NY Strip 12 oz", "ea", 12],
    ["Beef & Pork", "Cowboy Ribeye 16 oz", "ea", 6],
    ["Beef & Pork", "Tomahawk", "ea", 2],
    ["Beef & Pork", "Ground Angus", "lb", 20],
    ["Beef & Pork", "Lamb Chops", "lb", 6],
    ["Beef & Pork", "French Cut Pork Chop 14 oz", "ea", 10],
    ["Beef & Pork", "Applewood Bacon", "lb", 15],
    ["Beef & Pork", "Conecuh Sausage", "lb", 8],
    ["Beef & Pork", "Canadian Bacon", "lb", 4],
    ["Beef & Pork", "Boar's Head Black Forest Ham", "lb", 6],
    ["Beef & Pork", "Boar's Head Turkey", "lb", 6],
    ["Beef & Pork", "Corned Beef", "lb", 4],
    ["Beef & Pork", "Tasso", "lb", 3],
    ["Poultry", "Chicken Breast", "lb", 20],
    ["Poultry", "Chicken Tenders", "lb", 10],
    ["Poultry", "Duck Breast", "ea", 8],
    ["Produce", "Romaine", "cs", 2],
    ["Produce", "Iceberg Heads", "cs", 1],
    ["Produce", "Spring Mix", "cs", 2],
    ["Produce", "Fresh Spinach", "cs", 2],
    ["Produce", "Arugula", "cs", 1],
    ["Produce", "Heirloom Tomatoes", "lb", 10],
    ["Produce", "Grape Tomatoes", "cs", 2],
    ["Produce", "Green Tomatoes", "lb", 15],
    ["Produce", "Avocados", "cs", 1],
    ["Produce", "Brussels Sprouts", "lb", 10],
    ["Produce", "Asparagus", "lb", 8],
    ["Produce", "Broccoli / Broccolini", "lb", 8],
    ["Produce", "Mushrooms", "lb", 8],
    ["Produce", "Red Onions", "lb", 10],
    ["Produce", "Bell Peppers", "lb", 8],
    ["Produce", "Jalapeños", "lb", 3],
    ["Produce", "Lemons", "cs", 1],
    ["Produce", "Strawberries", "cs", 1],
    ["Produce", "Blueberries", "cs", 1],
    ["Produce", "Bananas", "cs", 1],
    ["Produce", "Mangoes", "ea", 12],
    ["Produce", "Sweet Potatoes", "cs", 1],
    ["Dairy & Eggs", "Shell Eggs", "cs", 3],
    ["Dairy & Eggs", "Heavy Cream", "qt", 12],
    ["Dairy & Eggs", "Butter", "lb", 20],
    ["Dairy & Eggs", "Whole Milk", "gal", 4],
    ["Dairy & Eggs", "Smoked Gouda", "lb", 6],
    ["Dairy & Eggs", "Swiss", "lb", 4],
    ["Dairy & Eggs", "Cheddar", "lb", 8],
    ["Dairy & Eggs", "Monterey Jack", "lb", 6],
    ["Dairy & Eggs", "Feta", "lb", 3],
    ["Dairy & Eggs", "Brie", "ea", 8],
    ["Dairy & Eggs", "Bleu Cheese", "lb", 3],
    ["Dairy & Eggs", "Parmesan", "lb", 5],
    ["Dairy & Eggs", "Goat Cheese", "lb", 3],
    ["Dairy & Eggs", "American Cheese", "lb", 4],
    ["Dry Goods", "Stone Ground Grits", "lb", 15],
    ["Dry Goods", "Penne", "lb", 10],
    ["Dry Goods", "Linguini", "lb", 10],
    ["Dry Goods", "All-Purpose Flour", "lb", 25],
    ["Dry Goods", "Panko", "lb", 8],
    ["Dry Goods", "Arborio Rice", "lb", 8],
    ["Dry Goods", "Puff Pastry Sheets", "cs", 1],
    ["Bread & Bakery", "Brioche Buns", "dz", 8],
    ["Bread & Bakery", "French Bread", "loaf", 12],
    ["Bread & Bakery", "Pita Bread", "dz", 6],
    ["Bread & Bakery", "Marble Rye", "loaf", 4],
    ["Bread & Bakery", "Sourdough", "loaf", 6],
    ["Bread & Bakery", "Wheat Bread", "loaf", 4],
  ];

  return [
    ...prep.map(([c, n, u, p]) => item("prep", c, n, u, p)),
    ...ordering.map(([c, n, u, p]) => item("ordering", c, n, u, p)),
  ];
}

function recipe(
  id: string,
  name: string,
  category: string,
  yieldAmt: string,
  prepTime: string,
  description: string,
  ingredients: Recipe["ingredients"],
  instructions: string[],
  notes?: string
): Recipe {
  return {
    id,
    name,
    category,
    yield: yieldAmt,
    prepTime,
    description,
    ingredients,
    instructions,
    notes,
    createdAt: now,
    updatedAt: now,
  };
}

export function seedRecipes(): Recipe[] {
  return [
    recipe(
      "lump-crab-cakes",
      "Fresh Lump Crab Cakes",
      "Seafood",
      "40 cakes (2 oz)",
      "45 minutes",
      "Tamara's handmade lump crab cakes, served with remoulade and fried spinach.",
      [
        { amount: "5 lb", item: "Fresh lump crab meat, picked" },
        { amount: "1½ cup", item: "Mayonnaise" },
        { amount: "3", item: "Eggs" },
        { amount: "2 tbsp", item: "Dijon mustard" },
        { amount: "2 tbsp", item: "Worcestershire" },
        { amount: "1 tbsp", item: "Old Bay" },
        { amount: "1 tsp", item: "Kosher salt" },
        { amount: "½ tsp", item: "White pepper" },
        { amount: "½ cup", item: "Minced scallion" },
        { amount: "¼ cup", item: "Minced red bell pepper" },
        { amount: "1½ cup", item: "Panko (plus more to coat)" },
        { amount: "2 tbsp", item: "Chopped parsley" },
      ],
      [
        "Drain crab well and pick for shell. Keep lumps as whole as possible.",
        "Whisk mayonnaise, eggs, Dijon, Worcestershire, Old Bay, salt, and pepper.",
        "Fold in scallion, pepper, parsley, then panko. Rest 5 minutes.",
        "Gently fold in crab. Do not mash the lumps.",
        "Scoop 2 oz cakes, flatten slightly, and dust with panko.",
        "Pan-sear in clarified butter until golden, or hold raw on parchment for service.",
        "Finish in a 375°F oven 4–6 minutes if needed. Serve with remoulade.",
      ],
      "Admin can replace this house-style starter recipe with Tamara's exact formula."
    ),
    recipe(
      "gumbo",
      "Shrimp, Crab & Crawfish Gumbo",
      "Soups",
      "4 gallons",
      "3 hours",
      "Dark-roux gumbo with Gulf shrimp, crab, and crawfish. Add oysters to order.",
      [
        { amount: "3 cups", item: "Vegetable oil" },
        { amount: "3 cups", item: "All-purpose flour" },
        { amount: "3 lb", item: "Holy trinity (onion, celery, bell pepper), small dice" },
        { amount: "8", item: "Garlic cloves, minced" },
        { amount: "6 oz", item: "Tomato paste" },
        { amount: "3 gal", item: "Shrimp or seafood stock" },
        { amount: "2 tbsp", item: "Cajun seasoning" },
        { amount: "2 tsp", item: "Thyme" },
        { amount: "4", item: "Bay leaves" },
        { amount: "1 lb", item: "Andouille or Conecuh, sliced" },
        { amount: "2 lb", item: "Gulf shrimp, peeled" },
        { amount: "1 lb", item: "Crawfish tails" },
        { amount: "1 lb", item: "Lump crab meat" },
        { amount: "to taste", item: "Salt, pepper, hot sauce, file powder" },
      ],
      [
        "Cook oil and flour over medium heat, stirring constantly, to a dark chocolate roux (25–40 minutes).",
        "Add trinity and cook until soft. Stir in garlic and tomato paste 2 minutes.",
        "Whisk in warm stock. Add seasoning, thyme, bay, and sausage. Simmer 45–60 minutes.",
        "Skim fat. Adjust body with stock or a little extra roux slurry.",
        "Add shrimp and crawfish in the last 8 minutes. Fold crab in off heat.",
        "Hold at 165°F. Garnish with rice or serve as cup/bowl. Oysters added per ticket.",
      ]
    ),
    recipe(
      "crawfish-joule",
      "Crawfish Joule Sauce",
      "Sauces",
      "1 gallon",
      "40 minutes",
      "The house crawfish cream used on shrimp stack, fried green tomatoes, and brunch benedicts.",
      [
        { amount: "8 oz", item: "Butter" },
        { amount: "2 cups", item: "Minced onion and bell pepper" },
        { amount: "4", item: "Garlic cloves" },
        { amount: "½ cup", item: "Flour" },
        { amount: "1 cup", item: "White wine" },
        { amount: "2 qt", item: "Seafood stock" },
        { amount: "1 qt", item: "Heavy cream" },
        { amount: "1 lb", item: "Crawfish tails" },
        { amount: "1 tbsp", item: "Cajun seasoning" },
        { amount: "1 tsp", item: "Paprika" },
        { amount: "to taste", item: "Salt, lemon, hot sauce" },
      ],
      [
        "Sweat onion, pepper, and garlic in butter until soft.",
        "Stir in flour and cook 3 minutes.",
        "Deglaze with wine, then whisk in stock and cream.",
        "Simmer until it coats a spoon. Season.",
        "Fold in crawfish and warm through. Do not boil hard after cream is in.",
      ]
    ),
    recipe(
      "hollandaise",
      "Classic Hollandaise",
      "Sauces",
      "2 quarts",
      "25 minutes",
      "Service hollandaise for eggs Benedict, catfish, and brunch plates.",
      [
        { amount: "18", item: "Egg yolks" },
        { amount: "¼ cup", item: "Water" },
        { amount: "¼ cup", item: "Lemon juice" },
        { amount: "2 lb", item: "Clarified butter, warm" },
        { amount: "to taste", item: "Kosher salt, cayenne, Tabasco" },
      ],
      [
        "Whisk yolks, water, and lemon over a gentle bain-marie to ribbon stage.",
        "Slowly stream in warm clarified butter until thick and glossy.",
        "Season. Hold in a warm thermos or at 140°F. Do not exceed 150°F.",
        "For sriracha, buffalo, tomato, or maple variants, fold flavoring in to taste just before service.",
      ],
      "Discard after 4 hours of service or if it breaks beyond repair."
    ),
    recipe(
      "crab-meat-pie",
      "Crab Meat Pie",
      "Appetizers",
      "12 pies",
      "50 minutes",
      "Signature puff pastry with lump crab, caramelized pecans, and meuniere.",
      [
        { amount: "12", item: "Puff pastry rounds or shells" },
        { amount: "2 lb", item: "Lump crab meat" },
        { amount: "4 oz", item: "Butter" },
        { amount: "1 cup", item: "Minced shallot" },
        { amount: "½ cup", item: "Caramelized pecans, chopped" },
        { amount: "½ cup", item: "Heavy cream" },
        { amount: "2 tbsp", item: "Parsley" },
        { amount: "to taste", item: "Salt, white pepper, lemon" },
        { amount: "2 cups", item: "Meuniere sauce, for service" },
      ],
      [
        "Bake pastry shells until golden and dry inside.",
        "Sweat shallot in butter. Add cream, reduce slightly, fold in crab and pecans.",
        "Season and fill shells. Hold warm.",
        "Plate with meuniere nappe and extra pecans.",
      ]
    ),
    recipe(
      "spinach-artichoke-dip",
      "Spinach & Artichoke Dip",
      "Appetizers",
      "1 gallon",
      "35 minutes",
      "Hot spinach, artichoke, and Monterey Jack dip with warm pita.",
      [
        { amount: "3 lb", item: "Chopped spinach, squeezed dry" },
        { amount: "2 lb", item: "Artichoke hearts, chopped" },
        { amount: "1 lb", item: "Cream cheese" },
        { amount: "1 lb", item: "Monterey Jack, shredded" },
        { amount: "8 oz", item: "Parmesan" },
        { amount: "2 cups", item: "Mayonnaise" },
        { amount: "1 cup", item: "Sour cream" },
        { amount: "6", item: "Garlic cloves, minced" },
        { amount: "1 tsp", item: "Crushed red pepper" },
        { amount: "to taste", item: "Salt, pepper, lemon" },
      ],
      [
        "Soften cream cheese. Mix with mayo, sour cream, garlic, and seasonings.",
        "Fold in spinach, artichoke, and cheeses.",
        "Bake in hotel pans at 350°F until bubbling and browned, about 25 minutes.",
        "Hold hot. Serve with warm pita.",
      ]
    ),
    recipe(
      "smoked-tuna-dip",
      "Smoked Tuna Dip",
      "Appetizers",
      "3 quarts",
      "20 minutes",
      "Bar favorite served with flatbread.",
      [
        { amount: "3 lb", item: "Smoked tuna, flaked" },
        { amount: "2 cups", item: "Mayonnaise" },
        { amount: "8 oz", item: "Cream cheese" },
        { amount: "¼ cup", item: "Lemon juice" },
        { amount: "2 tbsp", item: "Creole mustard" },
        { amount: "2 tbsp", item: "Minced red onion" },
        { amount: "2 tbsp", item: "Chopped parsley" },
        { amount: "1 tbsp", item: "Hot sauce" },
        { amount: "1 tsp", item: "Old Bay" },
      ],
      [
        "Beat cream cheese smooth, then blend in mayo, lemon, mustard, and seasonings.",
        "Fold in tuna, onion, and parsley. Keep some texture.",
        "Chill at least 1 hour. Taste and adjust lemon and heat.",
      ]
    ),
    recipe(
      "remoulade",
      "House Remoulade",
      "Sauces",
      "2 quarts",
      "15 minutes",
      "For crab cakes, calamari, poboys, and fried green tomatoes.",
      [
        { amount: "4 cups", item: "Mayonnaise" },
        { amount: "½ cup", item: "Creole mustard" },
        { amount: "¼ cup", item: "Ketchup" },
        { amount: "¼ cup", item: "Prepared horseradish" },
        { amount: "¼ cup", item: "Lemon juice" },
        { amount: "3 tbsp", item: "Hot sauce" },
        { amount: "¼ cup", item: "Minced celery" },
        { amount: "¼ cup", item: "Minced green onion" },
        { amount: "2 tbsp", item: "Minced parsley" },
        { amount: "1 tbsp", item: "Paprika" },
        { amount: "1 tsp", item: "Cajun seasoning" },
      ],
      [
        "Whisk all ingredients until even.",
        "Rest 30 minutes so flavors marry. Hold refrigerated.",
      ]
    ),
    recipe(
      "meuniere",
      "Meuniere Sauce",
      "Sauces",
      "2 quarts",
      "20 minutes",
      "Brown-butter lemon sauce for crab pie, shrimp and grits, and brunch plates.",
      [
        { amount: "2 lb", item: "Butter" },
        { amount: "½ cup", item: "Minced shallot" },
        { amount: "½ cup", item: "Lemon juice" },
        { amount: "¼ cup", item: "Worcestershire" },
        { amount: "¼ cup", item: "Chopped parsley" },
        { amount: "to taste", item: "Salt and white pepper" },
      ],
      [
        "Brown butter until nutty and golden. Add shallot 1 minute.",
        "Off heat, whisk in lemon and Worcestershire.",
        "Add parsley and season. For bacon meuniere, fold in crisp bacon lardons.",
        "Hold warm, not boiling.",
      ]
    ),
    recipe(
      "bread-pudding",
      "Homemade Bread Pudding with Bourbon Sauce",
      "Desserts",
      "2 hotel pans",
      "90 minutes",
      "House bread pudding with local pecans and bourbon sauce.",
      [
        { amount: "4 loaves", item: "Stale French or brioche, cubed" },
        { amount: "1 dozen", item: "Eggs" },
        { amount: "2 qt", item: "Half-and-half" },
        { amount: "3 cups", item: "Sugar" },
        { amount: "2 tbsp", item: "Vanilla" },
        { amount: "2 tsp", item: "Cinnamon" },
        { amount: "2 cups", item: "Toasted pecans" },
        { amount: "8 oz", item: "Butter (for sauce)" },
        { amount: "2 cups", item: "Brown sugar (for sauce)" },
        { amount: "1 cup", item: "Heavy cream (for sauce)" },
        { amount: "½ cup", item: "Bourbon (for sauce)" },
      ],
      [
        "Butter hotel pans. Pack in bread and pecans.",
        "Whisk eggs, dairy, sugar, vanilla, and cinnamon. Pour over bread and soak 20 minutes.",
        "Bake at 325°F in a water bath until set, 45–55 minutes.",
        "For sauce: melt butter and brown sugar, whisk in cream, simmer 3 minutes, add bourbon off heat.",
        "Spoon sauce tableside. For bananas Foster version, sauté bananas in brown sugar and rum and spoon over.",
      ]
    ),
    recipe(
      "gouda-grits",
      "Gouda Cheese Grits",
      "Sides",
      "2 gallons",
      "45 minutes",
      "Brunch and dinner grits — smoked gouda, stone ground.",
      [
        { amount: "2 qt", item: "Stone ground grits" },
        { amount: "1 gal", item: "Water or light stock" },
        { amount: "2 qt", item: "Whole milk" },
        { amount: "8 oz", item: "Butter" },
        { amount: "2 lb", item: "Smoked gouda, shredded" },
        { amount: "to taste", item: "Salt and white pepper" },
      ],
      [
        "Bring liquid to a simmer. Rain in grits while whisking.",
        "Cook low, stirring often, until tender, 30–40 minutes. Add milk as needed.",
        "Mount with butter and gouda. Season. Hold in a steam well, stirring to keep smooth.",
      ]
    ),
    recipe(
      "fried-green-tomatoes",
      "Fried Green Tomatoes",
      "Appetizers",
      "40 slices",
      "30 minutes",
      "Panko-crusted green tomatoes for appetizers, shrimp stack, and Benedict.",
      [
        { amount: "12", item: "Firm green tomatoes, ⅓-inch slices" },
        { amount: "2 cups", item: "Flour, seasoned" },
        { amount: "6", item: "Eggs, beaten with a splash of milk" },
        { amount: "4 cups", item: "Panko" },
        { amount: "to taste", item: "Salt, pepper, Cajun seasoning" },
      ],
      [
        "Season slices. Dredge flour, egg, then panko. Press crumbs on firmly.",
        "Hold on parchment, single layer, under refrigeration.",
        "Fry 350°F until golden. Salt immediately.",
        "Serve with crawfish joule, or top with crab and hollandaise.",
      ]
    ),
    recipe(
      "chicken-tamara",
      "Chicken Tamara",
      "Entrees",
      "12 portions",
      "60 minutes",
      "Bacon-wrapped chicken stuffed with asparagus and smoked gouda, Tasso cream, Parmesan risotto.",
      [
        { amount: "12", item: "Airline or thick chicken breasts" },
        { amount: "24", item: "Asparagus spears, blanched" },
        { amount: "12 oz", item: "Smoked gouda, sticks or shredded" },
        { amount: "24 slices", item: "Applewood bacon" },
        { amount: "to taste", item: "Salt, pepper" },
        { amount: "1 qt", item: "Tasso cream sauce" },
      ],
      [
        "Butterfly breasts. Season. Stuff with asparagus and gouda.",
        "Wrap with bacon and secure. Sear seam-side down.",
        "Roast at 375°F to 165°F internal.",
        "Rest 5 minutes. Slice on a bias. Nap with Tasso cream over risotto.",
      ]
    ),
    recipe(
      "bbq-shrimp",
      "New Orleans BBQ Shrimp",
      "Appetizers",
      "1 gallon broth / 20 portions",
      "30 minutes",
      "Herb-and-garlic Worcestershire butter broth with Gulf shrimp and grilled bread.",
      [
        { amount: "1 lb", item: "Butter" },
        { amount: "1 cup", item: "Minced garlic" },
        { amount: "2 tbsp", item: "Cracked black pepper" },
        { amount: "2 tbsp", item: "Rosemary and thyme, chopped" },
        { amount: "1 cup", item: "Worcestershire" },
        { amount: "1 cup", item: "Beer or seafood stock" },
        { amount: "½ cup", item: "Lemon juice" },
        { amount: "2 tbsp", item: "Hot sauce" },
        { amount: "5 lb", item: "Head-on or 16/20 Gulf shrimp" },
      ],
      [
        "Melt butter. Stew garlic, pepper, and herbs 2 minutes.",
        "Add Worcestershire, beer/stock, lemon, and hot sauce. Simmer 10 minutes.",
        "Hold broth. Sauté shrimp to order in broth until just pink.",
        "Serve in a bowl with grilled bread for dunking.",
      ]
    ),
    recipe(
      "creme-brulee",
      "Creme Brulee",
      "Desserts",
      "16 ramekins",
      "50 minutes + chill",
      "Baked custard finished with caramelized turbinado sugar and fruit.",
      [
        { amount: "1 qt", item: "Heavy cream" },
        { amount: "1", item: "Vanilla bean or 1 tbsp vanilla" },
        { amount: "8", item: "Egg yolks" },
        { amount: "¾ cup", item: "Sugar" },
        { amount: "as needed", item: "Turbinado sugar for service" },
      ],
      [
        "Warm cream with vanilla. Temper into yolks whisked with sugar.",
        "Strain. Fill ramekins. Bake in a water bath at 300°F until just set, 30–40 minutes.",
        "Chill at least 4 hours.",
        "Dust turbinado and torch to glass. Garnish with fruit.",
      ]
    ),
    recipe(
      "honey-pecan-brie",
      "Honey Pecan Baked Brie",
      "Appetizers",
      "8 wheels",
      "25 minutes",
      "Puff pastry, Brie, honey, and pecans with pear chutney and pita.",
      [
        { amount: "8", item: "Small Brie wheels" },
        { amount: "8", item: "Puff pastry squares" },
        { amount: "1 cup", item: "Honey" },
        { amount: "2 cups", item: "Toasted pecans" },
        { amount: "1", item: "Egg wash" },
        { amount: "2 cups", item: "Pear chutney" },
      ],
      [
        "Place Brie on pastry. Top with honey and pecans. Wrap and seal.",
        "Egg wash. Bake 400°F until deep golden, 15–18 minutes.",
        "Rest 5 minutes. Plate over pear chutney with pita.",
      ]
    ),
    recipe(
      "pimento-cheese",
      "Gouda Pimento Cheese",
      "Spreads",
      "2 quarts",
      "15 minutes",
      "For ham & biscuit Benedict and the chicken pimento sandwich.",
      [
        { amount: "2 lb", item: "Smoked gouda, shredded" },
        { amount: "8 oz", item: "Sharp cheddar, shredded" },
        { amount: "1½ cup", item: "Mayonnaise" },
        { amount: "12 oz", item: "Diced pimentos, drained" },
        { amount: "1 tsp", item: "Onion powder" },
        { amount: "1 tsp", item: "Garlic powder" },
        { amount: "½ tsp", item: "Cayenne" },
        { amount: "to taste", item: "Salt and black pepper" },
      ],
      [
        "Fold everything together. Do not overmix into a paste.",
        "Chill 1 hour. Soften slightly before spreading.",
      ]
    ),
    recipe(
      "seafood-au-gratin",
      "Seafood Au Gratin",
      "Seafood",
      "12 portions",
      "40 minutes",
      "Shrimp, scallops, crawfish, and crab in a creamy cheese sauce with potatoes and vegetables.",
      [
        { amount: "1 lb", item: "Shrimp" },
        { amount: "1 lb", item: "Scallops" },
        { amount: "8 oz", item: "Crawfish tails" },
        { amount: "8 oz", item: "Lump crab" },
        { amount: "2 lb", item: "Par-cooked potatoes, sliced" },
        { amount: "1 qt", item: "Four-cheese cream sauce or crab mornay" },
        { amount: "8 oz", item: "Shredded cheese blend" },
        { amount: "as needed", item: "Sautéed vegetable medley" },
      ],
      [
        "Sear shrimp and scallops just until marked. Fold seafood into warm cheese sauce.",
        "Layer potatoes and seafood mixture in buttered dishes.",
        "Top with cheese. Bake 375°F until browned and 165°F in the center.",
        "Serve with sautéed vegetables.",
      ]
    ),
    recipe(
      "tasso-cream",
      "Tasso Cream Sauce",
      "Sauces",
      "2 quarts",
      "25 minutes",
      "For Chicken Tamara and seafood risotto.",
      [
        { amount: "8 oz", item: "Tasso, small dice" },
        { amount: "4 oz", item: "Butter" },
        { amount: "1 cup", item: "Minced shallot" },
        { amount: "½ cup", item: "Flour" },
        { amount: "1 cup", item: "White wine" },
        { amount: "1 qt", item: "Chicken stock" },
        { amount: "1 qt", item: "Heavy cream" },
        { amount: "to taste", item: "Black pepper and Cajun seasoning" },
      ],
      [
        "Render tasso in butter. Add shallot until soft.",
        "Stir in flour 2 minutes. Deglaze with wine.",
        "Whisk in stock and cream. Simmer until nappe.",
        "Season lightly — tasso is already salty.",
      ]
    ),
    recipe(
      "chocolate-lava-cake",
      "Chocolate Lava Cake",
      "Desserts",
      "16 cakes",
      "35 minutes",
      "Warm chocolate and creme brulee-filled cake with whipped cream, caramel, and strawberries.",
      [
        { amount: "1 lb", item: "Dark chocolate" },
        { amount: "1 lb", item: "Butter" },
        { amount: "8", item: "Eggs plus 8 yolks" },
        { amount: "2 cups", item: "Sugar" },
        { amount: "1 cup", item: "Flour" },
        { amount: "16", item: "Creme brulee or ganache inserts, frozen" },
      ],
      [
        "Melt chocolate and butter together. Cool slightly.",
        "Whisk eggs, yolks, and sugar until pale. Fold in chocolate, then flour.",
        "Butter and sugar ramekins. Fill halfway, add frozen insert, cover with batter.",
        "Bake 425°F about 12 minutes until edges are set and centers are soft.",
        "Invert, garnish with whipped cream, caramel, and strawberries.",
      ]
    ),
  ];
}
